services:
  pravobot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pravobot
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ../cyber_shield.db:/app/cyber_shield.db
    networks:
      - pravonet

networks:
  pravonet:
